### ISSUE TITLE
meta: use cases

### ISSUE THREAD

**Issue by adg** [upspin/upspin#19]
These are the use cases we aspire to cover before the end of 2016.
- [x] Provide a reliable shared Unix file system, accessible to one user from multiple machines. (#20)
- [x] Provide a simple backup system. (#22)
- [x] Provide an upspin tree for managing GitHub issues. (#23)
- [ ] Support syncing from remote locations (Sydney / Mountain View).
- [x] Support working on upspin trees with standard tools like Photoshop. (#24)
- [x] Provide a simple setup process for new users.
- [ ] Support working in disconnected environments (airplanes).
- [x] Provide a mechanism for key recovery. 
- [ ] Use an upspin directory as `$HOME` (stretch)

**Comment by adg** [comment]
I'm going to close this. It was helpful in planning the release, but its utility has waned.
